### ISSUE TITLE
mx_valid_with_fallback method -  false negatives

### ISSUE THREAD

**Issue by eddiej** [hallelujah/valid_email#51]
I'm getting a number of false negatives with the mx_valid_with_fallback? method, up to 3% on the examples I've tried. I'm guessing this might be connection issues when polling the dns records - is there an option to return valid in cases where the mx records cant be retrieved?

```ruby
valid = 0; invalid = 0; email = 'eddie@mac.com';
1000.times do 
    (ValidateEmail.mx_valid_with_fallback?(email) ? valid+=1 : invalid+=1 ) 
end; 
puts "#{email}\r\ninvalid: #{invalid}\r\nvalid: #{valid}"
```

```ruby
eddie@mac.com
invalid: 8
valid: 992
```

**Comment by hallelujah** [comment]
Hi @eddiej I just ran your example 5 times and they all give me:

```ruby
eddie@mac.com
invalid: 0
valid: 1000
```

Your problem may be something related to your network but then I guess Resolv::DNS should raise an error instead

I think I can consider adding options to Resolv::DNS.open in order to use your own DNS cache so no network issues if your cache is local to the system

**Comment by eddiej** [comment]
Thanks @hallelujah, it seems as if Resolv::DNS doesn't raise any errors if it fails to connect, it just returns 0 records which is why I"m getting false negatives.

**Comment by hallelujah** [comment]
Well closing. This is infrastructure/network related
